# Generated by Django 2.1.5 on 2019-01-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.FileField(default='static/blog/images/blog_icon.png', upload_to=''),
        ),
    ]
